spring:
  security:
    oauth2:
      client:
        registration:
          id-austria:
            client-id: https://www.e-movimento.com/springboot # your-client-id-from-id-austria
            client-secret: x6UlL4fodvBn2jRNlzpQv21jLadQl3r2plcf9PKGTlc= # your-client-secret-from-id-austria
            authorization-grant-type: authorization_code
            scope: openid,profile
            redirect-uri: https://localhost:8443/login/oauth2/code/id-austria # that uri must be set as one of the allowed redirect-uris (https only for id-austria)
        provider:
          id-austria:
            issuer-uri: https://eid2.oesterreich.gv.at

server:
  port: 8443
  ssl: # to enable ssl for https://localhost:8080 since ID-Austria does not allow redirect-uri http://localhost... even on test instance
    enabled: true
    key-store: classpath:localhost.p12
    key-store-password: admin
    key-store-type: PKCS12
    key-alias: tomcat
    
    
logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
        web.FilterChainProxy: DEBUG
        oauth2:
          client: DEBUG
          client.endpoint: TRACE